import { Counter } from "./counter";
import { ChatAgent } from "./agents/chat";
import { routeAgentRequest } from "agents";

// Export the Durable Object classes
export { Counter };
export { ChatAgent };

// Env type is provided globally by worker-configuration.d.ts (generated by `wrangler types`)

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // Route agent requests (handles /agents/* paths including WebSocket upgrades)
    // routeAgentRequest returns null if the path doesn't match /agents/...
    const agentResponse = await routeAgentRequest(request, env);
    if (agentResponse) {
      return agentResponse;
    }

    // API routes
    if (url.pathname.startsWith("/api/")) {
      // Counter endpoints
      const counterMatch = url.pathname.match(/^\/api\/counter\/(.*?)(\/increment|\/decrement)?$/);

      if (counterMatch) {
        const name = counterMatch[1];
        const action = counterMatch[2];

        // Get or create a Durable Object stub for this counter
        const stub = env.COUNTERS.getByName(name);

        if (!action || action === "") {
          // Get current value
          const count = await stub.getCounterValue();
          return Response.json({ name, count });
        } else if (action === "/increment") {
          const count = await stub.increment();
          return Response.json({ name, count, action: "incremented" });
        } else if (action === "/decrement") {
          const count = await stub.decrement();
          return Response.json({ name, count, action: "decremented" });
        }
      }

      return Response.json({ name: "Cloudflare" });
    }

    // For run_worker_first routes that aren't agents or API, fall through to assets
    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<Env>;
